
global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nvidia_smi_exporter'
    static_configs:
      - targets: ['nvidia_smi_exporter:9835']
