version: '3.3'  # Specify the version compatible with your Docker Compose setup

services:
  ollama:
    image: ollama/ollama:latest
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/11434' || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    networks:
      - default

  open-webui:
    image: ghcr.io/open-webui/open-webui
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_BASE_URL
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL
      - WEBUI_SECRET_KEY
      - USE_CUDA_DOCKER
      - DATABASE_URL
    restart: unless-stopped
    volumes:
      - open_webui:/app/backend/data
    networks:
      - default

  postgres:
    image: postgres:${PG_MAJOR:-latest}
    environment:
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      - default

networks:
  default:  # Properly define the default network
    driver: bridge

volumes:
  ollama:  # Define the named volumes correctly
  open_webui:
  postgres:
